Repository ogi02/Odyssey, pull requests merged in 2020-04, with the labels that each got.

#11 [Fix] Checks input once more before registering user in order to avoid possible errors
  odyssey/client/src/Authentication/authentication_management.js
Labels: bug

#12 Update UI for current pages
  odyssey/client/public/favicon.png
  odyssey/client/public/images/Gabi/cover_picture
  odyssey/client/public/images/Gabi/profile_picture
  odyssey/client/public/images/src/Home.png
  odyssey/client/public/index.html
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Home.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Profiles/Profile.svelte
  odyssey/flask_profile/profile.py
  odyssey/info.log
  odyssey/info.log.1
Labels: enhancement

#13 Search engine
  odyssey/.gitignore
  odyssey/Pipfile
  odyssey/Pipfile.lock
  odyssey/client/.gitignore
  odyssey/client/package-lock.json
  odyssey/client/package.json
  odyssey/client/public/images/ogi/profile_picture
  odyssey/client/public/images/ogi1/cover_picture
  odyssey/client/public/images/ogi2/profile_picture
  odyssey/client/public/index.html
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Authentication/BecomeCreator.svelte
  odyssey/client/src/Authentication/authentication_helpers.js
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Helpers/Field.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Navigation/NotFound.svelte
  odyssey/client/src/Navigation/Route.svelte
  odyssey/client/src/Navigation/Router.svelte
  odyssey/client/src/Navigation/Search.svelte
  odyssey/client/src/Profiles/ChangePic.svelte
  odyssey/client/src/Profiles/EditProfile.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/js/fetch.js
  odyssey/client/src/js/helpers.js
  odyssey/client/src/js/routes.js
  odyssey/client/src/js/stores.js
  odyssey/error.log
  odyssey/flask_authentication/authentication.py
  odyssey/flask_classes/active_user.py
  odyssey/flask_classes/user.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_logging/log_config.py
  odyssey/flask_profile/profile.py
  odyssey/info.log
  odyssey/info.log.1
  odyssey/main.py
Labels: enhancement

#14 Follow/unfollow user functionality
  odyssey/client/package-lock.json
  odyssey/client/public/images/Dancho/cover_picture
  odyssey/client/public/images/Dancho/profile_picture
  odyssey/client/public/images/Gabi3/cover_picture
  odyssey/client/public/images/Gabi3/profile_picture
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/Profiles/profile_management.js
  odyssey/flask_classes/info.py
  odyssey/flask_follow/follow.py
  odyssey/main.py
Labels: enhancement

#15 Tiers and subscription
  odyssey/client/.gitignore
  odyssey/client/package-lock.json
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Profiles/ChangePic.svelte
  odyssey/client/src/Profiles/CreateTier.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/js/routes.js
  odyssey/flask_classes/info.py
  odyssey/flask_classes/tier.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_follow/follow.py
  odyssey/flask_profile/profile.py
  odyssey/flask_tier/tier_actions.py
  odyssey/main.py
Labels: enhancement

#16 Posts - Only Mongo and Flask
  odyssey/client/package-lock.json
  odyssey/flask_classes/post.py
  odyssey/flask_classes/tier.py
  odyssey/flask_post/post_actions.py
  odyssey/main.py
Labels: enhancement

#17 Authentication unit tests
  odyssey/flask_authentication/authentication.py
  odyssey/flask_classes/user.py
  odyssey/flask_profile/profile.py
  odyssey/main.py
  odyssey/tests/test_authentication.py
Labels: enhancement

#20 Hotfix info.py
  odyssey/flask_classes/info.py
Labels: bug fix

#21 Validators tests
  odyssey/flask_validators/email_validator.py
  odyssey/flask_validators/username_validator.py
  odyssey/tests/test_validators.py
Labels: enhancement
