Repository ogi02/Odyssey, pull requests merged in 2020-06, with the labels that each got.

#41 [FE-17] Error handling for Create Tier form
  odyssey/client/src/Tiers/CreateTier.svelte
  odyssey/client/src/Tiers/MyTiers.svelte
  odyssey/client/src/Tiers/UserTiers.svelte
  odyssey/flask_classes/tier.py
  odyssey/flask_validators/tier_name_validator.py
  odyssey/flask_validators/tier_price_validator.py
  odyssey/main.py
Labels: enhancement

#43 [Fix] Fixed extensive Svelte condition blocks
  odyssey/client/src/Giveaways/MyGiveaways.svelte
  odyssey/client/src/Giveaways/UserGiveaways.svelte
  odyssey/client/src/Surveys/MySurveys.svelte
  odyssey/client/src/Surveys/UserSurveys.svelte
Labels: bug fix

#42 [Fix] Removed Commissions tab
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
Labels: bug fix

#44 [FE-19] Update UI on all forms (Create Tier form)
  odyssey/client/src/Tiers/CreateTier.svelte
Labels: enhancement

#45 [FE-19] Update UI on all forms (Create Post form)
  odyssey/client/src/Posts/CreatePost.svelte
Labels: enhancement

#48 [FE-24] Update Navbar and Homepage
  odyssey/client/src/Home.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Navigation/Search.svelte
Labels: enhancement

#47 [FE-19] Update UI on all forms (Change Pictures, Edit Profile)
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy/camera_icon.png
  odyssey/client/src/Profiles/ChangePic.svelte
  odyssey/client/src/Profiles/EditProfile.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
Labels: enhancement

#51 [FE-19] Update UI on all forms (User Profile)
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
Labels: enhancement

#50 [FE-19] Update UI on all forms (Create Giveaway)
  odyssey/client/src/Giveaways/CreateGiveaway.svelte
Labels: enhancement

#49 [FE-19] Update UI on all forms (Create Survey)
  odyssey/client/src/Surveys/CreateSurvey.svelte
Labels: enhancement

#52 [US-1] Set Up Mail Service
  odyssey/Pipfile
  odyssey/Pipfile.lock
  odyssey/flask_authentication/authentication.py
  odyssey/flask_authentication/images/facebook2x.png
  odyssey/flask_authentication/images/instagram2x.png
  odyssey/flask_authentication/images/linkedin2x.png
  odyssey/flask_authentication/images/twitter2x.png
  odyssey/main.py
  odyssey/requirements.txt
  odyssey/templates/beefree-uo9t4ro6un.html
Labels: bug fix, enhancement

#53 [US-3] Create video for TUES FEST 2020
  odyssey/client/public/images/Kohaku/06-04-2020-00-17-46
  odyssey/client/public/images/Kohaku/06-04-2020-00-19-56
  odyssey/client/public/images/Kohaku/06-04-2020-00-21-30
  odyssey/client/public/images/Kohaku/06-04-2020-00-24-13
  odyssey/client/public/images/Kohaku/06-04-2020-00-26-42
  odyssey/client/public/images/Kohaku/cover_picture
  odyssey/client/public/images/Kohaku/profile_picture
  odyssey/client/public/images/testing/cover_picture
  odyssey/client/public/images/testing/profile_picture
  odyssey/client/public/images/testuser1/cover_picture
  odyssey/client/public/images/testuser1/profile_picture
  odyssey/client/src/Giveaways/MyGiveaways.svelte
  odyssey/client/src/Giveaways/UserGiveaways.svelte
  odyssey/client/src/Posts/MyPosts.svelte
  odyssey/client/src/Posts/UserPosts.svelte
  odyssey/client/src/Surveys/MySurveys.svelte
  odyssey/client/src/Surveys/UserSurveys.svelte
Labels: bug fix, enhancement

#54 [FE-20] Fix routing issues
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Authentication/BecomeCreator.svelte
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Home.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/js/helpers.js
  odyssey/client/src/js/stores.js
  odyssey/main.py
Labels: bug fix, enhancement

#55 [BE-11] Constant URLs for Databases
  odyssey/database_config.py
  odyssey/flask_checks/user_checks.py
  odyssey/flask_classes/creator_specific.py
  odyssey/flask_classes/giveaway.py
  odyssey/flask_classes/info.py
  odyssey/flask_classes/post.py
  odyssey/flask_classes/survey.py
  odyssey/flask_classes/tier.py
  odyssey/flask_classes/user.py
  odyssey/main.py
  odyssey/tests/test_authentication.py
  odyssey/tests/test_edit_profile.py
  odyssey/tests/test_follow.py
  odyssey/tests/test_posts.py
  odyssey/tests/test_tiers.py
  odyssey/tests/test_validators.py
Labels: enhancement

#56 [US-2] Set Up Mail Verification
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy_test_profile/06-04-2020-12-44-46
  odyssey/client/public/images/testing/cover_picture
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Home.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/flask_authentication/authentication.py
  odyssey/flask_classes/user.py
  odyssey/templates/activation_email.html
  odyssey/tests/test_authentication.py
  odyssey/tests/test_edit_profile.py
  odyssey/tests/test_follow.py
  odyssey/tests/test_posts.py
  odyssey/tests/test_tiers.py
Labels: enhancement

#57 [FE-23] Relative URLs for HTTP requests
  README.md
  odyssey/.flaskenv
  odyssey/client/package.json
  odyssey/client/public/images/ogi1/06-05-2020-15-29-46
  odyssey/client/public/images/ogi1/06-05-2020-15-35-12
  odyssey/client/public/images/ogi1/06-05-2020-15-46-13
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Giveaways/CreateGiveaway.svelte
  odyssey/client/src/Giveaways/MyGiveaways.svelte
  odyssey/client/src/Giveaways/UserGiveaways.svelte
  odyssey/client/src/Home.svelte
  odyssey/client/src/Navigation/NavBar.svelte
  odyssey/client/src/Navigation/Search.svelte
  odyssey/client/src/Posts/CreatePost.svelte
  odyssey/client/src/Posts/MyPosts.svelte
  odyssey/client/src/Posts/UserPosts.svelte
  odyssey/client/src/Profiles/ChangePic.svelte
  odyssey/client/src/Profiles/EditProfile.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/Profiles/profile_management.js
  odyssey/client/src/Surveys/CreateSurvey.svelte
  odyssey/client/src/Surveys/MySurveys.svelte
  odyssey/client/src/Surveys/UserSurveys.svelte
  odyssey/client/src/Tiers/CreateTier.svelte
  odyssey/client/src/Tiers/UserTiers.svelte
  odyssey/client/src/js/fetch.js
  odyssey/client/src/js/helpers.js
Labels: enhancement

#58 [BE-12] Fix session usage
  odyssey/.flaskenv
  odyssey/client/public/images/ogi1/06-06-2020-01-06-53
  odyssey/client/src/js/fetch.js
  odyssey/database_config.py
  odyssey/flask_authentication/authentication.py
  odyssey/flask_checks/user_checks.py
  odyssey/flask_classes/active_user.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_follow/follow.py
  odyssey/flask_giveaway/giveaway_actions.py
  odyssey/flask_post/post_actions.py
  odyssey/flask_profile/profile.py
  odyssey/flask_survey/survey_actions.py
  odyssey/flask_tier/tier_actions.py
  odyssey/flask_validators/tier_name_validator.py
  odyssey/flask_validators/tier_price_validator.py
  odyssey/main.py
  odyssey/templates/activation_email.html
  odyssey/tests/test_authentication.py
  odyssey/tests/test_edit_profile.py
  odyssey/tests/test_follow.py
  odyssey/tests/test_posts.py
  odyssey/tests/test_tiers.py
  odyssey/tests/test_validators.py
Labels: enhancement

#59 [FE-23] Become Creator UI
  odyssey/client/src/Authentication/BecomeCreator.svelte
Labels: enhancement
