Repository ogi02/Odyssey, pull requests merged in 2020-05, with the labels that each got.

#23 Set up continuous integration
  .github/workflows/pythonpackage.yml
  odyssey/requirements.txt
Labels: enhancement

#24 Giveaways
  odyssey/flask_classes/giveaway.py
  odyssey/flask_giveaway/giveaway_actions.py
  odyssey/main.py
Labels: enhancement

#25 [FE-12] User Interface for Posts
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy_test_profile/cover_picture
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy_test_profile/profile_picture
  odyssey/client/public/images/test/05-01-2020-23-20-11
  odyssey/client/public/images/test/05-02-2020-22-53-57
  odyssey/client/public/images/test/05-02-2020-23-50-05
  odyssey/client/src/Posts/CreatePost.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/flask_classes/post.py
  odyssey/flask_classes/survey.py
  odyssey/flask_post/post_actions.py
  odyssey/flask_profile/profile.py
  odyssey/logs/error.log
  odyssey/logs/error.log.1
  odyssey/logs/info.log
  odyssey/logs/info.log.1
  odyssey/tests/test_edit_profile.py
Labels: enhancement

#26 [TS-2] Follow tests
  odyssey/flask_authentication/authentication.py
  odyssey/flask_classes/info.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_follow/follow.py
  odyssey/tests/test_authentication.py
  odyssey/tests/test_edit_profile.py
  odyssey/tests/test_follow.py
  odyssey/tests/test_validators.py
Labels: enhancement

#27 [FE-13] User Interface for Surveys
  odyssey/client/public/images/ogi/05-03-2020-12-04-04
  odyssey/client/public/images/ogi/05-03-2020-12-25-12
  odyssey/client/public/images/ogi/05-03-2020-13-43-48
  odyssey/client/public/images/ogi1/05-03-2020-11-58-25
  odyssey/client/public/images/ogi1/05-03-2020-16-35-23
  odyssey/client/src/Profiles/CreateTier.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/Surveys/CreateSurvey.svelte
  odyssey/client/src/js/fetch.js
  odyssey/flask_classes/survey.py
  odyssey/flask_profile/profile.py
  odyssey/flask_survey/survey_actions.py
Labels: enhancement

#28 [BE-9] Update Roles Field in MongoDB
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/flask_classes/user.py
  odyssey/flask_profile/profile.py
Labels: enhancement

#29 [TS-2] Tier Tests
  odyssey/flask_classes/creator_specific.py
  odyssey/flask_classes/tier.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_tier/tier_actions.py
  odyssey/tests/test_authentication.py
  odyssey/tests/test_edit_profile.py
  odyssey/tests/test_follow.py
  odyssey/tests/test_tiers.py
  odyssey/tests/test_validators.py
Labels: enhancement

#30 [FE-14] User Interface for Giveaway Events
  odyssey/client/public/images/Dancho/cover_picture
  odyssey/client/public/images/Dancho/profile_picture
  odyssey/client/public/images/Gabi/cover_picture
  odyssey/client/public/images/Gabi/profile_picture
  odyssey/client/public/images/Gabi3/cover_picture
  odyssey/client/public/images/Gabi3/profile_picture
  odyssey/client/public/images/ogi1/05-03-2020-23-08-10
  odyssey/client/public/images/ogi1/05-03-2020-23-08-47
  odyssey/client/src/Giveaways/CreateGiveaway.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/flask_classes/giveaway.py
  odyssey/flask_giveaway/giveaway_actions.py
  odyssey/flask_profile/profile.py
Labels: enhancement

#31 [TS-2] Tests README.md
  CONTRIBUTING.md
  README.md
  odyssey/.coverage
  odyssey/logs/error.log
  odyssey/logs/info.log
  odyssey/logs/info.log.1
  odyssey/tests/README.md
Labels: documentation

#33 [FE-16] New UI for Login and Registration
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Helpers/Error.svelte
  odyssey/client/src/Helpers/Field.svelte
  odyssey/client/src/js/helpers.js
  odyssey/flask_validators/email_validator.py
  odyssey/flask_validators/username_validator.py
  odyssey/tests/test_validators.py
Labels: enhancement

#34 [FE-15] Update UI for new features
  odyssey/client/public/images/jojy/05-08-2020-00-02-56
  odyssey/client/public/images/jojy/05-08-2020-00-09-50
  odyssey/client/public/images/jojy/cover_picture
  odyssey/client/public/images/jojy/profile_picture
  odyssey/client/public/images/ogi/05-08-2020-12-16-20
  odyssey/client/public/images/ogi/05-08-2020-12-21-23
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/flask_classes/survey.py
  odyssey/flask_survey/survey_actions.py
  odyssey/logs/error.log
  odyssey/logs/info.log
  odyssey/logs/info.log.1
Labels: enhancement

#35 [FE-15] Update UI for new features
  odyssey/client/package-lock.json
  odyssey/client/public/index.html
  odyssey/client/src/Giveaways/MyGiveaways.svelte
  odyssey/client/src/Posts/MyPosts.svelte
  odyssey/client/src/Profiles/MyProfile.svelte
  odyssey/client/src/Surveys/MySurveys.svelte
  odyssey/client/src/Tiers/CreateTier.svelte
  odyssey/client/src/Tiers/MyTiers.svelte
  odyssey/flask_post/post_actions.py
  odyssey/flask_profile/profile.py
Labels: enhancement

#36 [TS-3] Tests for posts, surveys, giveaways, commissions
  odyssey/Pipfile
  odyssey/Pipfile.lock
  odyssey/flask_classes/post.py
  odyssey/flask_post/post_actions.py
  odyssey/tests/test_posts.py
Labels: enhancement, integration test

#37 [Fix] Removed undefined values when not creator
  odyssey/client/src/Profiles/MyProfile.svelte
Labels: bug fix

#38 [Fix] Fixed wrong percentage on surveys
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/Surveys/MySurveys.svelte
Labels: bug fix

#39 [FE-18] Feed for My Profile and User Profile
  odyssey/client/src/Giveaways/UserGiveaways.svelte
  odyssey/client/src/Posts/UserPosts.svelte
  odyssey/client/src/Profiles/UserProfile.svelte
  odyssey/client/src/Profiles/profile_management.js
  odyssey/client/src/Surveys/UserSurveys.svelte
  odyssey/client/src/Tiers/UserTiers.svelte
  odyssey/flask_classes/survey.py
Labels: enhancement
