Repository ogi02/Odyssey, pull requests merged in 2020-03, with the labels that each got.

#1 Users
  .DS_Store
  README.md
  odyssey/.flaskenv
  odyssey/api.py
  odyssey/api/.DS_Store
  odyssey/api/.flaskenv
  odyssey/api/.gitignore
  odyssey/api/Pipfile
  odyssey/api/Pipfile.lock
  odyssey/api/__pycache__/nestedDict.cpython-37.pyc
  odyssey/api/__pycache__/testing.cpython-37.pyc
  odyssey/api/__pycache__/users.cpython-37.pyc
  odyssey/api/client/.gitignore
  odyssey/api/client/README.md
  odyssey/api/client/package-lock.json
  odyssey/api/client/package.json
  odyssey/api/client/public/favicon.png
  odyssey/api/client/public/global.css
  odyssey/api/client/public/index.html
  odyssey/api/client/rollup.config.js
  odyssey/api/client/src/App.svelte
  odyssey/api/client/src/Authentication/Authentication.svelte
  odyssey/api/client/src/Authentication/Error.svelte
  odyssey/api/client/src/Authentication/Field.svelte
  odyssey/api/client/src/Authentication/authentication_helpers.js
  odyssey/api/client/src/Authentication/authentication_management.js
  odyssey/api/client/src/fetch.js
  odyssey/api/client/src/main.js
  odyssey/api/creatorSpecific.py
  odyssey/api/info.py
  odyssey/api/main.py
  odyssey/api/makefile
  odyssey/api/nestedDict.py
  odyssey/api/user.py
  odyssey/makefile
  odyssey/templates/index.html
Labels: enhancement

#2 Become creator
  README.md
  odyssey/api/client/package-lock.json
  odyssey/api/client/package.json
  odyssey/api/client/src/App.svelte
  odyssey/api/client/src/Authentication/Authentication.svelte
  odyssey/api/client/src/Authentication/BecomeCreator.svelte
  odyssey/api/client/src/Authentication/authentication_management.js
  odyssey/api/client/src/Helpers/Countries.svelte
  odyssey/api/client/src/Helpers/Error.svelte
  odyssey/api/client/src/Helpers/Field.svelte
  odyssey/api/creatorSpecific.py
  odyssey/api/main.py
Labels: documentation, enhancement

#3 Profile page
  odyssey/api/client/package-lock.json
  odyssey/api/client/src/App.svelte
  odyssey/api/client/src/Authentication/BecomeCreator.svelte
  odyssey/api/client/src/Profiles/Profile.svelte
  odyssey/api/client/src/Profiles/Profile.svlt
  odyssey/api/creatorSpecific.py
  odyssey/api/info.py
  odyssey/api/main.py
  odyssey/api/user.py
Labels: enhancement

#4 Hotfix/login fix
  .DS_Store
  odyssey/.DS_Store
  odyssey/.flaskenv
  odyssey/.gitignore
  odyssey/Pipfile
  odyssey/api/.DS_Store
  odyssey/api/.flaskenv
  odyssey/api/.gitignore
  odyssey/api/Pipfile.lock
  odyssey/api/__pycache__/nestedDict.cpython-37.pyc
  odyssey/api/__pycache__/testing.cpython-37.pyc
  odyssey/api/__pycache__/users.cpython-37.pyc
  odyssey/api/client/.gitignore
  odyssey/api/client/package-lock.json
  odyssey/api/client/src/Profiles/Profile.svlt
  odyssey/client/.gitignore
  odyssey/client/README.md
  odyssey/client/package.json
  odyssey/client/public/favicon.png
  odyssey/client/public/global.css
  odyssey/client/public/index.html
  odyssey/client/rollup.config.js
  odyssey/client/src/App.svelte
  odyssey/client/src/Authentication/Authentication.svelte
  odyssey/client/src/Authentication/BecomeCreator.svelte
  odyssey/client/src/Authentication/authentication_helpers.js
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Helpers/Countries.svelte
  odyssey/client/src/Helpers/Error.svelte
  odyssey/client/src/Helpers/Field.svelte
  odyssey/client/src/Profiles/Profile.svelte
  odyssey/client/src/fetch.js
  odyssey/client/src/main.js
  odyssey/creatorSpecific.py
  odyssey/info.py
  odyssey/main.py
  odyssey/makefile
  odyssey/nestedDict.py
  odyssey/user.py
Labels: bug

#5 Image handling
  odyssey/client/.gitignore
  odyssey/client/public/index.html
  odyssey/client/src/Authentication/authentication_helpers.js
  odyssey/client/src/Authentication/authentication_management.js
  odyssey/client/src/Helpers/Field.svelte
  odyssey/client/src/Profiles/ChangePic.svelte
  odyssey/client/src/Profiles/Profile.svelte
  odyssey/client/src/fetch.js
  odyssey/client/src/helpers.js
  odyssey/creatorSpecific.py
  odyssey/helpers.py
  odyssey/info.py
  odyssey/main.py
  odyssey/nestedDict.py
Labels: enhancement

#9 [New]Added logging to all current files
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy/cover_picture
  odyssey/client/public/images/_FpCerpd9Z7SIbjmN81Jy/profile_picture
  odyssey/client/src/Authentication/BecomeCreator.svelte
  odyssey/client/src/Profiles/Profile.svelte
  odyssey/error.log
  odyssey/flask_authentication/authentication.py
  odyssey/flask_creator/become_creator.py
  odyssey/flask_logging/log_config.py
  odyssey/flask_profile/profile.py
  odyssey/info.log
  odyssey/main.py
Labels: enhancement

#10 Dev documentation
  README.md
Labels: documentation
